api:
    build: .
    dockerfile: docker-api.dockerfile
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1773:1773"

client:
    build: .
    dockerfile: docker-client.dockerfile
    container_name: client
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3308:3308"

identityserver:
    build: .
    dockerfile: docker-identityserver.dockerfile
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"